name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 17

    - name: Build React App
      run: |
        yarn install # Install Dependencies
        CI=false yarn run build # CI=false to ignore warnings

    - name: Install Surge
      run: yarn global add surge

    - name: Deploy to Surge
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: ${{ secrets.SURGE_DOMAIN }}
        project: './build'
        login: ${{ secrets.SURGE_LOGIN }}
        token: ${{ secrets.SURGE_TOKEN }}